### ISSUE TITLE
[help] when i run the bot i get this error

### ISSUE THREAD

**Issue by mina9999** [matthewladams/TikBot#1]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 258, in static_login
    data = yield from self.request(Route('GET', '/users/@me'))
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: Unauthorized (status code: 401): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 123, in <module>
    client.run(os.getenv('TOKEN'))
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 519, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 490, in start
    yield from self.login(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 416, in login
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 346, in _login_1
    data = yield from self.http.static_login(token, bot=is_bot)
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 262, in static_login
    raise LoginFailure('Improper token has been passed.') from e
discord.errors.LoginFailure: Improper token has been passed.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fc03e5eff60>

**Comment by danyildiabin** [comment]
You can replace (line 164) in main.py from `client.run(os.getenv('TOKEN'))` to `client.run("bot_token")` where `bot_token` is your secret code discord gave you.
Also don't forget change (line 61) to specified channel name.
If you want you can remove (line 61 & 62) to make bot active in all channels.
